#!/bin/bash

# Color Clicker - 快速参考指南

echo "========================================="
echo "  Color Clicker - Linux/Ubuntu 版本"
echo "========================================="
echo ""
echo "📂 项目位置:"
echo "   ubuntu-tools/color-clicker/"
echo ""
echo "🚀 快速启动:"
echo "   ./run.sh"
echo ""
echo "🔧 手动编译:"
echo "   cargo build --release"
echo ""
echo "▶️  运行程序:"
echo "   ./target/release/color-clicker"
echo ""
echo "🧪 运行测试:"
echo "   cargo test"
echo ""
echo "📖 查看文档:"
echo "   - README.md       (使用说明)"
echo "   - BUILD-GUIDE.md  (构建指南)"
echo "   - PROJECT-SUMMARY.md (项目总结)"
echo ""
echo "⚙️  配置文件: config.json"
echo ""
echo "========================================="
